# Generated by Django 4.2.3 on 2023-07-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0003_assets_yesterday_conversation_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='alltime_conversation_intensity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assets',
            name='category',
            field=models.CharField(choices=[('Forex', 'Forex'), ('Cryptocurrency', 'Cryptocurrency'), ('Stocks', 'Stocks'), ('Commodities', 'Commodities'), ('NFTs', 'Non-Fungible Tokens'), ('Indices', 'Indices'), ('Bonds', 'Bonds'), ('ETFs', 'Exchange-Traded Funds'), ('REIT', 'Real Estate Investment Trusts'), ('Others', 'Others')], default='Others', max_length=100),
        ),
        migrations.AlterField(
            model_name='assets',
            name='current_conversation_intensity',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='assets',
            name='month_conversation_intensity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assets',
            name='week_conversation_intensity',
            field=models.IntegerField(default=0),
        ),
    ]
