# Generated by Django 4.2.3 on 2023-07-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0006_alter_assets_alltime_conversation_intensity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='market_price',
            field=models.CharField(default='1.0', max_length=100),
        ),
    ]
