# Generated by Django 4.2.3 on 2023-07-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0010_assets_market_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='category',
            field=models.CharField(choices=[('All', 'All'), ('Forex', 'Forex'), ('Cryptocurrency', 'Cryptocurrency'), ('Stocks', 'Stocks'), ('Commodities', 'Commodities'), ('NFTs', 'Non-Fungible Tokens'), ('Indices', 'Indices'), ('Bonds', 'Bonds'), ('ETFs', 'Exchange-Traded Funds'), ('REIT', 'Real Estate Investment Trusts'), ('Others', 'Others')], default='Others', max_length=100),
        ),
    ]
