# Generated by Django 4.2.3 on 2023-09-11 12:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0011_alter_assets_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.TextField()),
                ('post_image', models.ImageField(upload_to='post_images')),
                ('no_post_likes', models.CharField(default=0, max_length=10)),
                ('post_date', models.DateTimeField(default=datetime.datetime.now)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bat_app.assets')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bat_app.profile')),
            ],
        ),
    ]
