# Generated by Django 4.2.3 on 2023-09-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0012_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_sentiment',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='posts',
            name='no_post_likes',
            field=models.IntegerField(default=0),
        ),
    ]
