# Generated by Django 4.2.3 on 2023-09-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0013_posts_post_sentiment_alter_posts_no_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_sentiment',
            field=models.CharField(choices=[('Bullish', 'Bullish'), ('Bearish', 'Bearish')], max_length=100, null=True),
        ),
    ]
