# Generated by Django 4.2.3 on 2023-09-13 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0014_alter_posts_post_image_alter_posts_post_sentiment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorites',
        ),
    ]
