# Generated by Django 4.2.3 on 2023-09-25 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0017_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='new_drop',
        ),
    ]
