# Generated by Django 4.2.3 on 2023-09-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0018_remove_assets_new_drop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='alltime_conversation_intensity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='assets',
            name='current_conversation_intensity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='assets',
            name='month_conversation_intensity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='assets',
            name='week_conversation_intensity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
