# Generated by Django 4.2.3 on 2023-09-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0019_alter_assets_alltime_conversation_intensity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='subscribers',
            field=models.IntegerField(default=0),
        ),
    ]
