# Generated by Django 4.2.3 on 2023-09-25 16:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0020_assets_subscribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_text', models.TextField()),
                ('article_link', models.TextField()),
                ('article_author', models.CharField(max_length=100)),
                ('article_date', models.DateTimeField(default=datetime.datetime.now)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bat_app.assets')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bat_app.profile')),
            ],
        ),
    ]
