# Generated by Django 4.2.3 on 2023-09-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0021_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='insights',
            field=models.TextField(blank=True),
        ),
    ]
