# Generated by Django 4.2.3 on 2023-09-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0022_assets_insights'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='article_polarity',
            field=models.TextField(blank=True),
        ),
    ]
