# Generated by Django 4.2.3 on 2023-09-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0024_remove_articles_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_polarity',
            field=models.TextField(blank=True),
        ),
    ]
