# Generated by Django 4.2.3 on 2023-09-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0026_alter_assets_market_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='market_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
