# Generated by Django 4.2.3 on 2023-09-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0027_alter_assets_market_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='market_price',
            field=models.CharField(max_length=100),
        ),
    ]
