# Generated by Django 4.2.3 on 2023-09-26 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0031_alter_articles_asset_alter_posts_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='bat_app.assets'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bat_app.profile'),
        ),
    ]
