# Generated by Django 4.2.3 on 2023-09-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0032_alter_posts_asset_alter_posts_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='market_price',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
