# Generated by Django 4.2.3 on 2023-10-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0035_conversation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(related_name='conversations', to='bat_app.profile'),
        ),
    ]
