# Generated by Django 4.2.3 on 2023-10-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0037_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content_type',
            field=models.CharField(choices=[('Text', 'Text'), ('Image', 'Image'), ('Video', 'Video')], default='Text', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='media_file',
            field=models.FileField(null=True, upload_to='message_media'),
        ),
    ]
