# Generated by Django 4.2.3 on 2023-10-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0038_message_content_type_message_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='message_media'),
        ),
    ]
