# Generated by Django 4.2.3 on 2023-10-20 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0039_alter_message_media_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avatar',
            new_name='profile_picture',
        ),
    ]
