# Generated by Django 4.2.3 on 2023-10-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0041_message_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='messages',
            field=models.ManyToManyField(related_name='messages', to='bat_app.message'),
        ),
    ]
