# Generated by Django 4.2.3 on 2023-10-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0044_profile_bio_profile_joined_profile_no_of_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='bearish_poll',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assets',
            name='bullish_poll',
            field=models.IntegerField(default=0),
        ),
    ]
