# Generated by Django 4.2.3 on 2023-10-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0045_assets_bearish_poll_assets_bullish_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='bearish_poll',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='bullish_poll',
        ),
        migrations.AddField(
            model_name='assets',
            name='profiles_voted_bearish',
            field=models.ManyToManyField(blank=True, related_name='bearish_assets', to='bat_app.profile'),
        ),
        migrations.AddField(
            model_name='assets',
            name='profiles_voted_bullish',
            field=models.ManyToManyField(blank=True, related_name='bullish_assets', to='bat_app.profile'),
        ),
    ]
