# Generated by Django 4.2.3 on 2023-10-22 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bat_app', '0046_remove_assets_bearish_poll_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPollStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_polls', models.PositiveIntegerField(default=0)),
                ('bullish_count', models.PositiveIntegerField(default=0)),
                ('bearish_count', models.PositiveIntegerField(default=0)),
                ('bullish_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('bearish_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
