# Generated by Django 4.2.3 on 2023-10-23 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0047_dailypollstatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart', models.FileField(blank=True, null=True, upload_to='signal_charts')),
                ('order_type', models.CharField(max_length=100)),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('takeprofit', models.DecimalField(decimal_places=4, max_digits=10)),
                ('stoploss', models.DecimalField(decimal_places=4, max_digits=10)),
                ('expiry', models.DateTimeField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bat_app.assets')),
                ('downvotes', models.ManyToManyField(blank=True, related_name='profile_downvotes', to='bat_app.profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_signal', to='bat_app.profile')),
                ('upvotes', models.ManyToManyField(blank=True, related_name='profile_upvotes', to='bat_app.profile')),
            ],
        ),
    ]
