# Generated by Django 4.2.3 on 2023-10-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0051_signal_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='analysis',
            field=models.TextField(blank=True),
        ),
    ]
