# Generated by Django 4.2.3 on 2023-10-24 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0052_alter_signal_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bat_app.profile')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='category',
            field=models.CharField(choices=[('Inbox', 'Inbox'), ('Request', 'Request')], default='Request', max_length=100),
        ),
        migrations.CreateModel(
            name='CommunityMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('Text', 'Text'), ('Image', 'Image'), ('Video', 'Video')], default='Text', max_length=10)),
                ('text', models.TextField()),
                ('media_file', models.FileField(blank=True, null=True, upload_to='message_media')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bat_app.community')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bat_app.profile')),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='messages',
            field=models.ManyToManyField(related_name='group_messages', to='bat_app.communitymessage'),
        ),
        migrations.AddField(
            model_name='community',
            name='participants',
            field=models.ManyToManyField(related_name='group_conversations', to='bat_app.profile'),
        ),
    ]
