# Generated by Django 4.2.3 on 2023-10-24 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0054_community_cover_image_community_display_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='date_started',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
