# Generated by Django 4.2.3 on 2023-10-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0055_community_date_started'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='no_of_followers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='no_of_following',
        ),
        migrations.AddField(
            model_name='profile',
            name='cover_picture',
            field=models.ImageField(blank=True, upload_to='profile_cover_image'),
        ),
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='profile_followers', to='bat_app.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='profile_following', to='bat_app.profile'),
        ),
        migrations.AlterField(
            model_name='community',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='group_messages', to='bat_app.communitymessage'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_dp_image'),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(blank=True, choices=[('forex', 'Forex'), ('crypto', 'Cryptocurrency'), ('stocks', 'Stocks'), ('investing', 'Investing'), ('trading', 'Trading')], to='bat_app.interest'),
        ),
    ]
