# Generated by Django 4.2.3 on 2023-10-25 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0058_remove_posts_no_post_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='bat_app.assets'),
        ),
    ]
