# Generated by Django 4.2.3 on 2023-10-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0061_explore_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='asset',
        ),
        migrations.AddField(
            model_name='posts',
            name='asset',
            field=models.ManyToManyField(blank=True, related_name='posts_asset', to='bat_app.assets'),
        ),
    ]
