# Generated by Django 4.2.3 on 2023-10-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0062_remove_posts_asset_posts_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='asses_post', to='bat_app.posts'),
        ),
    ]
