# Generated by Django 4.2.3 on 2023-10-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0063_assets_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forex', models.FileField(blank=True, upload_to='forex_data')),
                ('stocks', models.FileField(blank=True, upload_to='stocks_data')),
                ('crypto', models.FileField(blank=True, upload_to='crypto_data')),
                ('nft', models.FileField(blank=True, upload_to='nft_data')),
                ('commodities', models.FileField(blank=True, upload_to='commodities_data')),
                ('indices', models.FileField(blank=True, upload_to='indices_data')),
                ('bonds', models.FileField(blank=True, upload_to='bonds_data')),
                ('etfs', models.FileField(blank=True, upload_to='etfs_data')),
                ('reits', models.FileField(blank=True, upload_to='reits_data')),
                ('others', models.FileField(blank=True, upload_to='others_data')),
            ],
        ),
        migrations.AlterField(
            model_name='assets',
            name='avatar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assets',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='asset_post', to='bat_app.posts'),
        ),
    ]
