# Generated by Django 4.2.3 on 2023-10-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0064_data_alter_assets_avatar_alter_assets_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='assets',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='bat_app.profile'),
        ),
    ]
