# Generated by Django 4.2.3 on 2023-11-25 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0065_remove_assets_subscribers_assets_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='avatar',
            new_name='logo',
        ),
    ]
