# Generated by Django 4.2.3 on 2023-11-30 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0066_rename_avatar_assets_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='community',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='community',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='communitymessage',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communitymessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='dailypollstatistics',
            name='user',
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='upvotes',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='alltime_conversation_intensity',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='alltime_conversation_volume',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='alltime_sentiment',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='category',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='current_conversation_intensity',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='current_conversation_volume',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='current_sentiment',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='month_conversation_intensity',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='month_conversation_volume',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='month_sentiment',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='profiles_voted_bearish',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='profiles_voted_bullish',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='week_conversation_intensity',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='week_conversation_volume',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='week_sentiment',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='yesterday_conversation_volume',
        ),
        migrations.AddField(
            model_name='assets',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='assets',
            name='city',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='assets',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assets',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assets',
            name='employees',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='assets',
            name='exchange',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assets',
            name='icon',
            field=models.ImageField(blank=True, upload_to='asset_icon'),
        ),
        migrations.AddField(
            model_name='assets',
            name='list_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='assets',
            name='locale',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assets',
            name='market_cap',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='assets',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assets',
            name='postal_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assets',
            name='sentiment',
            field=models.CharField(choices=[('Bullish', 'Bullish'), ('Bearish', 'Bearish'), ('Neutral', 'Neutral')], default='Neutral', max_length=100),
        ),
        migrations.AddField(
            model_name='assets',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assets',
            name='ticker_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assets',
            name='website',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assets',
            name='logo',
            field=models.ImageField(blank=True, upload_to='asset_logo'),
        ),
        migrations.DeleteModel(
            name='Community',
        ),
        migrations.DeleteModel(
            name='CommunityMessage',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='DailyPollStatistics',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Signal',
        ),
    ]
