# Generated by Django 4.2.3 on 2023-11-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0068_alter_assets_list_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='article_polarity',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='article_text',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='asset',
        ),
        migrations.AddField(
            model_name='articles',
            name='article_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='article_image',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='article_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='article_publisher',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='article_publisher_logo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='article_publisher_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='article_title',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='assets',
            field=models.ManyToManyField(blank=True, related_name='articles_assets', to='bat_app.assets'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_link',
            field=models.TextField(blank=True),
        ),
    ]
