# Generated by Django 4.2.3 on 2023-12-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0069_remove_articles_article_polarity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='article_keywords',
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=100)),
                ('articles', models.ManyToManyField(blank=True, related_name='articles_interests', to='bat_app.articles')),
                ('posts', models.ManyToManyField(blank=True, related_name='posts_interests', to='bat_app.posts')),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='posts_interests', to='bat_app.interests'),
        ),
        migrations.AddField(
            model_name='articles',
            name='article_keywords',
            field=models.ManyToManyField(blank=True, related_name='articles_interests', to='bat_app.interests'),
        ),
    ]
