# Generated by Django 4.2.3 on 2023-12-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat_app', '0071_community_conversation_alter_posts_post_sentiment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='profiles_voted_bearish',
            field=models.ManyToManyField(blank=True, related_name='bearish_assets', to='bat_app.profile'),
        ),
        migrations.AddField(
            model_name='assets',
            name='profiles_voted_bullish',
            field=models.ManyToManyField(blank=True, related_name='bullish_assets', to='bat_app.profile'),
        ),
    ]
